class DisplayManager:

    def __init__(self, voice_list, lfo_list, adsr_list):

        self.voice_list = voice_list
        self.lfo_list = lfo_list
        self.adsr_list = adsr_list
        self.line1 = ""
        self.line2 = ""

    def update(self, update_tup):

        #line1, line2 = self.get_lines(update_tup)

        line1 = "Hello"
        line2 = "Testing"

        diff1 = self.diff_line(self.line1, line1)
        diff2 = self.diff_line(self.line2, line2)

        self.line1 = line1
        self.line2 = line2

        return diff1, diff2  # lists of tuples [(index, run of characters)]
        # this lets us only update the LCD characters that have changed

    def get_lines(self, update_tup):

        actual_object, param_name, value = update_tup  # unpacking the tuple generated by the Controls object
        printable_index = 999  # a placeholder indicator that something has gone very wrong
        for ls in self.voice_list, self.lfo_list, self.adsr_list:
            if actual_object in ls:
                # so the user can see LFO1, LFO2...
                printable_index = ls.index(actual_object) + 1
                break

        if actual_object in self.adsr_list or actual_object in self.lfo_list:
            # these objects are printable so we just pretty print them and insert their number
            outa, outb = actual_object.pretty_print()
            outa %= printable_index

        elif actual_object in self.voice_list:
            # can't fit all voice params on one display so we just display one at a time
            outa = "VOICE %i" % printable_index
            outb = "%s: %i" % (param_name, value)  # todo: pretty conversion e.g. cutoff into Hz

        return outa, outb

    def diff_line(self, old_line, new_line):

        """Detect only the characters that changed"""

        while len(new_line) < len(old_line):
            new_line += " "  # add spaces to overwrite the longer old line

        oldlen = len(old_line)
        newlen = len(new_line)

        minlen = min(oldlen, newlen)

        runs = []  # start index and a run of characters that need to be replaced
        index = 0

        runstart = 0
        run = []
        accumulating = False

        while index < minlen:
            old = old_line[index]
            new = new_line[index]

            if old == new:
                if run:  # don't append the empty list first time round
                    accumulating = False
                    runs.append((runstart, run))
                    runstart = 0
                    run = []
            else:
                if not accumulating:
                    accumulating = True
                    runstart = index
                run.append(new)

            index += 1

        if accumulating:  # make sure we catch the run if the line was different right
            # up until the last character
            runs.append((runstart, run))

        if oldlen < len(new_line):
            runs.append((oldlen, new_line[oldlen:]))

        return runs